name: PowerShell Test Script

on: [push]

jobs:
  checkout_repo:
    runs-on: windows-latest
    outputs:
      repoPath: ${{ steps.checkout_repo.outputs.repo-path }}
    steps:
    - name: Checkout Repository
      id: checkout_repo
      uses: actions/checkout@v2
    - name: Upload repo content as artifact
      uses: actions/upload-artifact@v2
      with:
        name: repo-content
        path: ${{ github.workspace }}

  run-powershell-1:
    needs: checkout_repo
    runs-on: windows-latest
    steps:
    - name: Download repo content
      uses: actions/download-artifact@v2
      with:
        name: repo-content
    - name: Execute PowerShell Script
      run: .\Test.ps1
      shell: pwsh  # Ensures PowerShell Core is used

    - name: Send Email Notification
      if: always()  # This ensures that the email step runs even if the previous step fails
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: mailcluster.loopia.se
        server_port: 587
        username: richard@metavision.se 
        password: WWars_Richard
        subject: Plupp GitHub Action Result
        body: The plupp result of the GitHub Action is ${{ job.status }}.
        to: richard@metavision.se
        from: GitHub Actions <nopreply@github.com>

  run-powershell-2:
    needs: checkout_repo
    runs-on: windows-latest
    steps:
    - name: Download repo content
      uses: actions/download-artifact@v2
      with:
        name: repo-content
    - name: Execute PowerShell Script 2
      run: .\Test2.ps1
      shell: pwsh